### ***PANDAS PRACTICE***

In [1]:
print('THIS IS PANDAS PRATICE SET SOLUTIONS')

THIS IS PANDAS PRATICE SET SOLUTIONS

In [2]:
import pandas as pd

## ***1-->Load & Explore the Dataset***

In [3]:
electric_prod = pd.read_csv('/content/Electric_Production.csv')

In [4]:
electric_prod

          DATE  IPG2211A2N
0     1/1/1985     72.5052
1     2/1/1985     70.6720
2     3/1/1985     62.4502
3     4/1/1985     57.4714
4     5/1/1985     55.3151
..         ...         ...
392   9/1/2017     98.6154
393  10/1/2017     93.6137
394  11/1/2017     97.3359
395  12/1/2017    114.7212
396   1/1/2018    129.4048

[397 rows x 2 columns]

In [5]:
electric_prod.columns

Index(['DATE', 'IPG2211A2N'], dtype='object')

###### CHANGE TO DATE TIME FORMAT

In [6]:
electric_prod = pd.to_datetime(electric_prod['DATE'])

In [7]:
electric_prod

0     1985-01-01
1     1985-02-01
2     1985-03-01
3     1985-04-01
4     1985-05-01
         ...
392   2017-09-01
393   2017-10-01
394   2017-11-01
395   2017-12-01
396   2018-01-01
Name: DATE, Length: 397, dtype: datetime64[ns]

In [8]:
electric_prod.head()

0   1985-01-01
1   1985-02-01
2   1985-03-01
3   1985-04-01
4   1985-05-01
Name: DATE, dtype: datetime64[ns]

In [9]:
electric_prod.info()

<class 'pandas.core.series.Series'>
RangeIndex: 397 entries, 0 to 396
Series name: DATE
Non-Null Count  Dtype
--------------  -----
397 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 3.2 KB

In [10]:
electric_prod = pd.DataFrame(electric_prod)

In [11]:
electric_prod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DATE    397 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 3.2 KB

###  ***2-->Extract Time Components***

###### *Create new columns for year, month, and day using .dt.year, .dt.month, .dt.day.*

In [12]:
# CREATE NEW COLUMN

In [13]:
electric_prod['Year'] = electric_prod['DATE'].dt.year
electric_prod['Month'] = electric_prod['DATE'].dt.month
electric_prod['Day'] = electric_prod['DATE'].dt.day

In [14]:
electric_prod

          DATE  Year  Month  Day
0   1985-01-01  1985      1    1
1   1985-02-01  1985      2    1
2   1985-03-01  1985      3    1
3   1985-04-01  1985      4    1
4   1985-05-01  1985      5    1
..         ...   ...    ...  ...
392 2017-09-01  2017      9    1
393 2017-10-01  2017     10    1
394 2017-11-01  2017     11    1
395 2017-12-01  2017     12    1
396 2018-01-01  2018      1    1

[397 rows x 4 columns]

##### *Print a summary of how many records exist for each year.*

In [15]:
yearly_count = electric_prod['Year'].value_counts()

In [16]:
yearly_count

Year
1985    12
1986    12
1987    12
1988    12
1989    12
1990    12
1991    12
1992    12
1993    12
1994    12
1995    12
1996    12
1997    12
1998    12
1999    12
2000    12
2001    12
2002    12
2003    12
2004    12
2005    12
2006    12
2007    12
2008    12
2009    12
2010    12
2011    12
2012    12
2013    12
2014    12
2015    12
2016    12
2017    12
2018     1
Name: count, dtype: int64

###### *Print a summary of how many records exist for each Month*

In [17]:
month_counts = electric_prod['Month'].value_counts()

In [18]:
month_counts

Month
1     34
2     33
3     33
4     33
5     33
6     33
7     33
8     33
9     33
10    33
11    33
12    33
Name: count, dtype: int64

##  ***3-->Resampling & Aggregating Data***

In [31]:
# LOAD DATASET

electric_production = pd.read_csv('/content/Electric_Production.csv')

In [32]:
# CHANGE DATE INTO DATE-TIME

electric_production['DATE'] = pd.to_datetime(electric_production['DATE'])

In [34]:
# MAKE SOME NEW COLUMNS

electric_production['Year'] = electric_production['DATE'].dt.year
electric_production['Month'] = electric_production['DATE'].dt.month
electric_production['Day'] = electric_production['DATE'].dt.day

In [35]:
electric_production

          DATE  IPG2211A2N  Year  Month  Day
0   1985-01-01     72.5052  1985      1    1
1   1985-02-01     70.6720  1985      2    1
2   1985-03-01     62.4502  1985      3    1
3   1985-04-01     57.4714  1985      4    1
4   1985-05-01     55.3151  1985      5    1
..         ...         ...   ...    ...  ...
392 2017-09-01     98.6154  2017      9    1
393 2017-10-01     93.6137  2017     10    1
394 2017-11-01     97.3359  2017     11    1
395 2017-12-01    114.7212  2017     12    1
396 2018-01-01    129.4048  2018      1    1

[397 rows x 5 columns]

In [36]:
# LET SET DATE TO AN INDEX

electric_production.set_index('DATE', inplace=True)

In [37]:
electric_production

            IPG2211A2N  Year  Month  Day
DATE
1985-01-01     72.5052  1985      1    1
1985-02-01     70.6720  1985      2    1
1985-03-01     62.4502  1985      3    1
1985-04-01     57.4714  1985      4    1
1985-05-01     55.3151  1985      5    1
...                ...   ...    ...  ...
2017-09-01     98.6154  2017      9    1
2017-10-01     93.6137  2017     10    1
2017-11-01     97.3359  2017     11    1
2017-12-01    114.7212  2017     12    1
2018-01-01    129.4048  2018      1    1

[397 rows x 4 columns]

##### *Resample the data to monthly averages using .resample('M').mean()*

In [42]:
# RESAMPLING

monthly_avg = electric_production.resample('M').mean()

<ipython-input-42-d1fa76c43420>:3: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_avg = electric_production.resample('M').mean()

In [43]:
monthly_avg

            IPG2211A2N    Year  Month  Day
DATE
1985-01-31     72.5052  1985.0    1.0  1.0
1985-02-28     70.6720  1985.0    2.0  1.0
1985-03-31     62.4502  1985.0    3.0  1.0
1985-04-30     57.4714  1985.0    4.0  1.0
1985-05-31     55.3151  1985.0    5.0  1.0
...                ...     ...    ...  ...
2017-09-30     98.6154  2017.0    9.0  1.0
2017-10-31     93.6137  2017.0   10.0  1.0
2017-11-30     97.3359  2017.0   11.0  1.0
2017-12-31    114.7212  2017.0   12.0  1.0
2018-01-31    129.4048  2018.0    1.0  1.0

[397 rows x 4 columns]

##### *Resample the data to weekly sums using .resample('W').sum().*

In [45]:
electric_production.resample('W').sum()

            IPG2211A2N  Year  Month  Day
DATE
1985-01-06     72.5052  1985      1    1
1985-01-13      0.0000     0      0    0
1985-01-20      0.0000     0      0    0
1985-01-27      0.0000     0      0    0
1985-02-03     70.6720  1985      2    1
...                ...   ...    ...  ...
2017-12-10      0.0000     0      0    0
2017-12-17      0.0000     0      0    0
2017-12-24      0.0000     0      0    0
2017-12-31      0.0000     0      0    0
2018-01-07    129.4048  2018      1    1

[1723 rows x 4 columns]

##### *Resample the data to monthly averages using .resample('M').mean()*

In [46]:
electric_production.resample('Y').mean()

<ipython-input-46-46537ecbe32c>:1: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  electric_production.resample('Y').mean()

            IPG2211A2N    Year  Month  Day
DATE
1985-12-31   62.165667  1985.0    6.5  1.0
1986-12-31   62.709892  1986.0    6.5  1.0
1987-12-31   65.740275  1987.0    6.5  1.0
1988-12-31   69.716358  1988.0    6.5  1.0
1989-12-31   71.895167  1989.0    6.5  1.0
1990-12-31   73.313433  1990.0    6.5  1.0
1991-12-31   75.111850  1991.0    6.5  1.0
1992-12-31   75.120908  1992.0    6.5  1.0
1993-12-31   77.678992  1993.0    6.5  1.0
1994-12-31   79.255058  1994.0    6.5  1.0
1995-12-31   82.060867  1995.0    6.5  1.0
1996-12-31   84.382417  1996.0    6.5  1.0
1997-12-31   84.236192  1997.0    6.5  1.0
1998-12-31   86.544075  1998.0    6.5  1.0
1999-12-31   89.190892  1999.0    6.5  1.0
2000-12-31   91.790125  2000.0    6.5  1.0
2001-12-31   91.460792  2001.0    6.5  1.0
2002-12-31   94.107075  2002.0    6.5  1.0
2003-12-31   95.700108  2003.0    6.5  1.0
2004-12-31   97.119225  2004.0    6.5  1.0
2005-12-31   99.208242  2005.0    6.5  1.0
2006-12-31   98.873225  2006.0    6.5  1.0
2007-12-31  101.984167  2007.0    6.5  1.0
2008-12-31  101.663992  2008.0    6.5  1.0
2009-12-31   98.829783  2009.0    6.5  1.0
2010-12-31  102.596883  2010.0    6.5  1.0
2011-12-31  102.290475  2011.0    6.5  1.0
2012-12-31   99.999992  2012.0    6.5  1.0
2013-12-31  102.337350  2013.0    6.5  1.0
2014-12-31  103.732783  2014.0    6.5  1.0
2015-12-31  103.052908  2015.0    6.5  1.0
2016-12-31  102.764375  2016.0    6.5  1.0
2017-12-31  101.944842  2017.0    6.5  1.0
2018-12-31  129.404800  2018.0    1.0  1.0

In [47]:
electric_production.resample('Y').sum()

<ipython-input-47-6ccb6650e40d>:1: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  electric_production.resample('Y').sum()

            IPG2211A2N   Year  Month  Day
DATE
1985-12-31    745.9880  23820     78   12
1986-12-31    752.5187  23832     78   12
1987-12-31    788.8833  23844     78   12
1988-12-31    836.5963  23856     78   12
1989-12-31    862.7420  23868     78   12
1990-12-31    879.7612  23880     78   12
1991-12-31    901.3422  23892     78   12
1992-12-31    901.4509  23904     78   12
1993-12-31    932.1479  23916     78   12
1994-12-31    951.0607  23928     78   12
1995-12-31    984.7304  23940     78   12
1996-12-31   1012.5890  23952     78   12
1997-12-31   1010.8343  23964     78   12
1998-12-31   1038.5289  23976     78   12
1999-12-31   1070.2907  23988     78   12
2000-12-31   1101.4815  24000     78   12
2001-12-31   1097.5295  24012     78   12
2002-12-31   1129.2849  24024     78   12
2003-12-31   1148.4013  24036     78   12
2004-12-31   1165.4307  24048     78   12
2005-12-31   1190.4989  24060     78   12
2006-12-31   1186.4787  24072     78   12
2007-12-31   1223.8100  24084     78   12
2008-12-31   1219.9679  24096     78   12
2009-12-31   1185.9574  24108     78   12
2010-12-31   1231.1626  24120     78   12
2011-12-31   1227.4857  24132     78   12
2012-12-31   1199.9999  24144     78   12
2013-12-31   1228.0482  24156     78   12
2014-12-31   1244.7934  24168     78   12
2015-12-31   1236.6349  24180     78   12
2016-12-31   1233.1725  24192     78   12
2017-12-31   1223.3381  24204     78   12
2018-12-31    129.4048   2018      1    1

In [48]:
electric_production.resample('Y').max()

<ipython-input-48-0835710e6106>:1: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  electric_production.resample('Y').max()

            IPG2211A2N  Year  Month  Day
DATE
1985-12-31     72.5052  1985     12    1
1986-12-31     73.3057  1986     12    1
1987-12-31     73.8152  1987     12    1
1988-12-31     79.8703  1988     12    1
1989-12-31     84.1949  1989     12    1
1990-12-31     84.3598  1990     12    1
1991-12-31     86.0214  1991     12    1
1992-12-31     85.2855  1992     12    1
1993-12-31     87.9464  1993     12    1
1994-12-31     94.1386  1994     12    1
1995-12-31     92.4532  1995     12    1
1996-12-31     98.9732  1996     12    1
1997-12-31     98.4613  1997     12    1
1998-12-31     94.7920  1998     12    1
1999-12-31    102.1348  1999     12    1
2000-12-31    102.4558  2000     12    1
2001-12-31    109.1081  2001     12    1
2002-12-31    102.9955  2002     12    1
2003-12-31    110.1807  2003     12    1
2004-12-31    113.7226  2004     12    1
2005-12-31    111.1614  2005     12    1
2006-12-31    111.5192  2006     12    1
2007-12-31    114.1036  2007     12    1
2008-12-31    114.8331  2008     12    1
2009-12-31    116.8316  2009     12    1
2010-12-31    119.0166  2010     12    1
2011-12-31    119.4880  2011     12    1
2012-12-31    113.0357  2012     12    1
2013-12-31    115.5010  2013     12    1
2014-12-31    124.2549  2014     12    1
2015-12-31    120.2696  2015     12    1
2016-12-31    117.0837  2016     12    1
2017-12-31    114.8505  2017     12    1
2018-12-31    129.4048  2018      1    1

### ***4--> Shifting Data for Trend Analysis***

###### *Create a new column "Previous Month Production" by shifting the data backward (.shift(1)).*

In [49]:
electric_production['Previous_Month_Production'] = electric_production['Month'].shift(1)

In [50]:
electric_production

            IPG2211A2N  Year  Month  Day  Previous_Month_Production
DATE
1985-01-01     72.5052  1985      1    1                        NaN
1985-02-01     70.6720  1985      2    1                        1.0
1985-03-01     62.4502  1985      3    1                        2.0
1985-04-01     57.4714  1985      4    1                        3.0
1985-05-01     55.3151  1985      5    1                        4.0
...                ...   ...    ...  ...                        ...
2017-09-01     98.6154  2017      9    1                        8.0
2017-10-01     93.6137  2017     10    1                        9.0
2017-11-01     97.3359  2017     11    1                       10.0
2017-12-01    114.7212  2017     12    1                       11.0
2018-01-01    129.4048  2018      1    1                       12.0

[397 rows x 5 columns]

##### *Create a new column "Next Month Projection" by shifting the data forward (.shift(-1)).*

In [52]:
electric_production['Next_Monthly_Projection'] = electric_production['Month'].shift(-1)

In [53]:
electric_production

,IPG2211A2N,Year,Month,Day,Previous_Month_Production,Next_Monthly_Projection
DATE,,,,,,
1985-01-01,72.5052,1985,1,1,NaN,2.0
1985-02-01,70.6720,1985,2,1,1.0,3.0
1985-03-01,62.4502,1985,3,1,2.0,4.0
1985-04-01,57.4714,1985,4,1,3.0,5.0
1985-05-01,55.3151,1985,5,1,4.0,6.0
...,...,...,...,...,...,...
2017-09-01,98.6154,2017,9,1,8.0,10.0
2017-10-01,93.6137,2017,10,1,9.0,11.0
2017-11-01,97.3359,2017,11,1,10.0,12.0
2017-12-01,114.7212,2017,12,1,11.0,1.0
2018-01-01,129.4048,2018,1,1,12.0,NaN